### ISSUE TITLE
Hud extremely slow to open in firefox

### ISSUE THREAD

**Issue by Izaic** [Zren/plasma-hud#9] opened 2019-03-30 00:37 UTC
On Kubuntu 19.04 the HUD takes a while to open for Firefox, other apps it opens fast however.

(By slow i mean up to 30 seconds)

**Comment by Zren** [comment] 2019-03-30 01:08
I'm guessing it's probably because it takes forever to "open" all your bookmark submenus.

Part of why I'm probably never use it for firefox is since my bookmark titles create a fair amount of false positives. I might consider adding a config option like `blacklistFirefoxBookmarks=true` and `blacklistFirefoxHistory=true`.

That won't solve the underlying performance issue though.

**Comment by Zren** [comment] 2019-04-18 16:14
It turns out I can change `GetLayout`'s `recursionDepth` to `-1` to fetch everything.

```diff
-item = dbusmenu_object_iface.GetLayout(item_id, 1, ["label", "children-display"])[1]
+item = dbusmenu_object_iface.GetLayout(item_id, -1, ["label", "children-display"])[1]
```

I rewrote the `expanse_all_menu_with_dbus` function to act more like the GTK code path.

```python

    """ expand nested dbus mwnu  """
    def explore_dbus_menu(item, path):
        item_id = item[0]
        item_props = item[1]
        item_children = item[2]

        if 'label' in item_props:
            new_path = path + " > " + item_props['label']
        else:
            new_path = path

        shortcut = None
        if 'shortcut' in item_props:
            shortcut = '+'.join(item_props['shortcut'][0])
            print('shortcut', shortcut)

        if len(item_children) == 0:
            if new_path not in blacklist:
                dbusmenu_item_dict[format_menuitem(new_path, shortcut)] = item_id
        else:
            blacklist.append(new_path)
            for child in item_children:
                explore_dbus_menu(child, new_path)


    """ expanse_all_menu_with_dbus """
    def expanse_all_menu_with_dbus(item, root, path):
        item_id = item[0]
        item_props = item[1]

        print("{:.3f}".format(time.perf_counter()), 'expanse_all', path)

        # expand if necessary
        if 'children-display' in item_props:
            dbusmenu_object_iface.AboutToShow(item_id)
            dbusmenu_object_iface.Event(item_id, "opened", "not used", dbus.UInt32(time.time())) #fix firefox
        try:
            item = dbusmenu_object_iface.GetLayout(item_id, -1, ["label", "children-display"])[1]
        except:
            return

        explore_dbus_menu(item, path)
```

I don't have many bookmarks, but it feels faster. Even dolphin and other non-gtk apps with large collection of submenues appear faster I think. No idea if it'll break some apps though. I'll push it to a new branch so people can test.

**Comment by Zren** [comment] 2019-04-18 20:09
I've pushed the https://github.com/Zren/plasma-hud/tree/performance branch if anyone would like to test.

I still need to make sure dynamically generated submenus are populated in the HUD. It looks like previous versions of mate-hud used `-1` but they use AboutToShow now...

https://github.com/ubuntu-mate/mate-hud/commit/bb3e37edd550b67faab85a3a0f85cf8db04bf991#diff-56c3c0fd5e032fbf53716f2b211fbffdL186

I wonder if I can improve on the current code to auto-expand the dynamic menus while also fetching the main check of menu items all at once.

**Comment by barolo** [comment] 2019-09-09 11:16
Was this merged? opening HUD in Firefox still has significant delay [5 sec+]

**Comment by Zren** [comment] 2019-09-17 04:02
Sorry, no, it was not merged to `master` yet.

Try the [`perf3` branch](https://github.com/Zren/plasma-hud/blob/perf3/usr/lib/plasma-hud/plasma-hud). It contains:

* Merged most of Pull Request #16
    * Removes the GTK dbus menu parsing (which was really fast) to use KDE's proxy menu (which was rather slow). This means I no longer need to duplicate work when adding a new feature.
    * Use `-1` depth when calling GetLayout, which should speed up the KDE proxy menu listing. Please confirm you aren't missing any menu items.
* "Init rofi_process before dbus GetLayout, then pipe menuKeys in after" (Issue #17) as well, which should prevent keypreses being dropped while loading the menu items.

`firefox-kde-opensuse` no longer exists, so I can't test the firefox global menu in Manjaro anymore.

Testing LibreOffice Calc: The KDE proxy menu appears feels just as fast as the previous GTK menu. I need to properly measure how long it takes to fetch the menu.

**Comment by Zren** [comment] 2019-09-28 16:08
I'll be removing `rofi -sync` by default. It waits until all menu items have been sent to rofi before showing the popup. I've refactored code to flush menu items as they are written.

The menu appears more or less instantly, giving visual feedback to pressing `Alt`, and continues to populate the menu as you type your search.

**Comment by barolo** [comment] 2019-09-28 19:30
> Sorry, no, it was not merged to `master` yet.
> 
> Try the [`perf3` branch](https://github.com/Zren/plasma-hud/blob/perf3/usr/lib/plasma-hud/plasma-hud). It contains:
> 
>     * Merged most of Pull Request #16
>       
>       * Removes the GTK dbus menu parsing (which was really fast) to use KDE's proxy menu (which was rather slow). This means I no longer need to duplicate work when adding a new feature.
>       * Use `-1` depth when calling GetLayout, which should speed up the KDE proxy menu listing. Please confirm you aren't missing any menu items.
> 
>     * "Init rofi_process before dbus GetLayout, then pipe menuKeys in after" (Issue #17) as well, which should prevent keypreses being dropped while loading the menu items.
> 
> 
> `firefox-kde-opensuse` no longer exists, so I can't test the firefox global menu in Manjaro anymore.
> 
> Testing LibreOffice Calc: The KDE proxy menu appears feels just as fast as the previous GTK menu. I need to properly measure how long it takes to fetch the menu.

Thank you, for me it's even easier to use global-menu enabled firefox than it was before [I'm on Gentoo] since it requires just a single patch which I'm stealing from Arch and it gets autoapplied during build

**Comment by Zren** [comment] 2020-07-26 02:07
The perf3 was merged into master a while ago.

**Closed by Zren** 2020-07-26 02:07 UTC

**Comment by dufferzafar** [comment] 2021-01-23 18:44
@Zren Even though, the menu now opens instantly on Firefox as well. Is there a way to remove the bookmark items from the menu?

**Comment by Zren** [comment] 2021-01-23 20:13
@dufferzafar: There isn't. The `try_dbusmenu_interface(...)` has a `wm_class` which you could check if it's `['Navigator', 'firefox']`.

There's a function for logging the wm_class here:  
https://github.com/Zren/plasma-hud/blob/master/usr/lib/plasma-hud/plasma-hud#L550-L552

You'd need to filter the `item_entry` before `write_menuitem(item_entry)` sends it to `rofi`.  
https://github.com/Zren/plasma-hud/blob/master/usr/lib/plasma-hud/plasma-hud#L545-L546

The issue is that the `item_entry` is the translated text. So while filtering all `item_entry.startswith('Bookmarks' + PATHSEPERATOR)` might work for english users, it won't work for other locales.
